name: sas-kernel
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyterlab=3
  - pip:
    - saspy>=3.7.1
    - pandas
    - sas_kernel
    - jlab-create-sas-file
    - sas2nb
    - swat
